### ISSUE TITLE
IRC chan?

### ISSUE THREAD

**Issue by stoke** [clanner/cocdp#1]
Hey clanner,

Great work here! I really appreciate all you put in this and i seriously want to thank you!

If you know other people interested in reversing coc (I for myself am trying to write a sort of proxy to dump live communication) we should really create an irc chan if it doesn't exist yet.

Again, thanks for everything!

**Comment by clanner** [comment]
i started this wiki after some talk about reversing CoC on http://androidgamehacks.net/. See the links on the [Home](..) page of the wiki. There you can find several others interested in this project.
