### ISSUE TITLE
DMCA

### ISSUE THREAD

**Issue by stoke** [clanner/cocdp#2]
I'm going to save every page of the wiki just in case anything real bad happens.

May I suggest going to bitbucket like [WhatsAPI](https://github.com/venomous0x/WhatsAPI) did?

**Comment by clanner** [comment]
I found that i can use the resource files directly from supercell, for example: [here](http://b46f744d64acd2191eda-3720c0374d47e9a0dd52be4d281c260f.r11.cf2.rackcdn.com/2b63d564d20bfa2c86d988b1e72848f1c2fa3095/csv/texts_patch.csv),  now i have to write some code which displays them directly from there.  and maybe host that on appspot orso.
