### ISSUE TITLE
cocprefs.py getting error ...

### ISSUE THREAD

**Issue by avisingh736** [clanner/cocdp#24]
While running this code getting error at #cocprefs.py line 126 at print function.
Can you please suggest me which python version prefer to this code

**Comment by clanner** [comment]
`cocprefs.py` is for python2.7

**Comment by avisingh736** [comment]
**Thank you for reply...**
_CMD at Administrator_
C:\Users\AVISINGH\Desktop\cocdp-master>python cocprefs.py "C:\Users\AVISINGH\Desktop\cocdp-master" **MyAndroidID** storage.xml
Traceback (most recent call last):
  File "cocprefs.py", line 144, in <module>
    handle_xmlfile(fn, args)
  File "cocprefs.py", line 129, _in handle_xmlfile
    with open(fn) as fh:_
**IOError: [Errno 13] Permission denied: 'C:\\Users\\AVISINGH\\Desktop\\cocdp-master'**

_is that any error or need some modifications on code ?_ becouse storage.xml file having full control where it placed(for user: AVISINGH,Administrator and System)

**Comment by clanner** [comment]
the command should be:

    python cocprefs.py --from <androidid>  "c:\users\.....\storage.xml"

**Comment by clanner** [comment]
the android id is the id from the file `shared_prefs/openudid_prefs.xml`

**Comment by avisingh736** [comment]
Thanks a lot it works for me.
