### ISSUE TITLE
Small update for messages.py

### ISSUE THREAD

**Issue by seppeduwe** [clanner/cocdp#9]
Clanner thank you for all this information. 
Some messages have changed (version 7.650). Below, a few changes I made. 
Currently I try to get as much as possible data from the clan. If anyone is doing the same, we can work together to get faster progress.
Sometimes I use "?" before name when it is not verified.

```
14302:{"name":"AskForAllianceData", "format":{"..6.000":"dd", "7.650..":"q"}},
24101:{"name":"OwnHomeData",
        "format":{
            "7.650..":"ddddqdddbsdqq?(qsddd)?(q)?(q)dddddssdddddddddddddd?(q)bdddd#[dd]#[dd]#[dd]#[dd]#[dd]#[dd]#[dd]#[dd]#[dd]#[ddd]#[d]#[d]#[dd]#[dd]#[dd]#[dd]ddd",
        },
            "7.650..":"? ? timestamp ? userid shieldtime ? ? ? compressed ? userid1 userid2 clan (id name badge ? level) ? () ? () ? ? ? alliance_units_count townhall_level username facebookid stars points diamonds diamonds2 ? ? trophies attacks_won attacks_lost defenses_won defenses_lost ? ? ? ? () ? ? ? ? ? storage [storage capacity] resources [resource quantity] units [unit quantity] spells [spell quantity] unit_upgrades [unit level] spell_upgrades [spell level] hero_upgrades [hero level] hero_health [hero health] hero_state [hero state] alliance_units [unit quantity level] tutorial_progress [] achievements [achievement] achievement_progress [achievement progress] npc_progress [] npc_gold [] npc_elixir []",
        },

24301:{"name":"AllianceData", "format":{
"7.650..":"qsdddddddddddddsdbdd#[qsddddddddbddbq]", #qsddqsdd
        },"fields":{
            "7.650..":"clanId clanName ? ? ?warsWon totalPoints requiredTrophies ?members ? ?clanLevel shield ?warFrequency ? clanPerksPoints ? description ? ? ? ? members [id name role level leagueLevel trophies troopsDonated troopsReceived rank previousRank newMember ?clanWarPreference ?clanWarPreference2 ? userId2]"}},

2:{"name":"Chat", "format":{
    "7.650..":"ddbqqsdddds",
},
   "fields":"id ? messageId userId homeId userName ? ? ? ? text"
   },
```

**Comment by seppeduwe** [comment]
Can someone fix number 1 of AllianceStream types
lstmtypes= {
1:{"name":"Donate", "format":{
"..6.999":"ddqqsddddbddd#[qddsdsdsdsds]bs", # actually: ddqqsddddbddd#[q#[ds]]bs
"7.000...":"bqqqsddddddd#[qddsdsdsdsds]bs",  # actually: bqqqsddddddd#[q#[ds]]bs
}},
Can't find it.
Thanks

**Comment by seppeduwe** [comment]
Have someone implemented nested formats?

**Comment by Viproz** [comment]
Would love to help as soon as I pass the Encryption packet, didn't it change too ?

What I receive looks like this :
000000105E7920901FB52DBCB586CEEE2B8E5DCF00000001A51400264522170FAAB63C5DA341EC2E9A10938DEFD74E9D6B4FBC0BD13A06A67B69C4A0341335499AE8D6A50D55F3521B2C89B65377E4C262ACA8610689422360CB8BAECEE45DA6C95A5F32B27D4B1B025F5E2B46ABBB1F9AD10ECFCC4735ECF2212B97825E8A7C0864CB88B7680CA1670B26A347AFF6EC6564C9779B1972D0D2DBAE4C22C118DBD9A161204820C01FE3E74AFB5FB39C97905E13CDFD1B7D322AD64892138BDFB883C51B1DDE22

So I can see a 16 bytes long string and then a dword but the rest makes no sense to me

**Comment by seppeduwe** [comment]
Viproz, i will share my code (based on clanners code).
I'll put it on github within 10minutes. (My code is still bad, so I will set it on private and invite you)
When the code is better I release it to the public

**Comment by Multiply** [comment]
@seppeduwe Can you invite me as well?
